-- MySQL Script generated by MySQL Workbench
-- seg 22 abr 2024 19:55:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `ID_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(70) NOT NULL,
  `EMAIL` VARCHAR(90) NOT NULL,
  `SENHA` VARCHAR(65) NOT NULL,
  `CANCELADO` CHAR(1) NOT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Atividade` (
  `ID_ATIVIDADE` INT NOT NULL AUTO_INCREMENT,
  `TITULO` VARCHAR(60) NOT NULL,
  `DESC` VARCHAR(250) NOT NULL,
  `DATA` DATE NOT NULL,
  `CANCELADO` CHAR(1) NOT NULL,
  PRIMARY KEY (`ID_ATIVIDADE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_Atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_Atividade` (
  `USUARIO.ID` INT NOT NULL,
  `ATIVIDADE.ID` INT NOT NULL,
  `DATA_ENTREGA` DATE NOT NULL,
  `NOTA` FLOAT NOT NULL,
  `CANCELADO` CHAR(1) NOT NULL,
  PRIMARY KEY (`USUARIO.ID`, `ATIVIDADE.ID`),
  INDEX `fk_Usuário_has_Atividade_Atividade1_idx` (`ATIVIDADE.ID` ASC) VISIBLE,
  INDEX `fk_Usuário_has_Atividade_Usuário_idx` (`USUARIO.ID` ASC) VISIBLE,
  CONSTRAINT `fk_Usuário_has_Atividade_Usuário`
    FOREIGN KEY (`USUARIO.ID`)
    REFERENCES `mydb`.`Usuario` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuário_has_Atividade_Atividade1`
    FOREIGN KEY (`ATIVIDADE.ID`)
    REFERENCES `mydb`.`Atividade` (`ID_ATIVIDADE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
